export const CROP_CONFIG = {
  MUTATIONS: [
    { name: "Wet", valueMultiplier: 2, chance: 0.01 },
    { name: "Chilled", valueMultiplier: 2, chance: 0.01 },
    { name: "Chocolate", valueMultiplier: 2, chance: 0 },
    { name: "Moonlit", valueMultiplier: 2, chance: 0 },
    { name: "Pollinated", valueMultiplier: 3, chance: 0 },
    { name: "Bloodlit", valueMultiplier: 4, chance: 0 },
    { name: "Plasma", valueMultiplier: 5, chance: 0 },
    { name: "HoneyGlazed", valueMultiplier: 5, chance: 0 },
    {
      name: "Frozen",
      valueMultiplier: 10,
      chance: 0,
      both: ["Wet", "Chilled"],
    },
    { name: "Golden", valueMultiplier: 20, chance: 0.01 },
    {
      name: "Zombified",
      valueMultiplier: 25,
      chance: 0.01,
      pet: ["gpChickenZombie"],
    },
    { name: "Twisted", valueMultiplier: 30, chance: 0 },
    { name: "Rainbow", valueMultiplier: 50, chance: 0.01 },
    { name: "Shocked", valueMultiplier: 100, chance: 0 },
    { name: "Celestial", valueMultiplier: 120, chance: 0 },
    { name: "Disco", valueMultiplier: 125, chance: 0 },
    { name: "VoidTouched", valueMultiplier: 135, chance: 0 },
  ],
  MBIAS: 3,
  GROWTH_BASE_OLD: 5 * 60 * 1000,
  GROWTH_BASE: 4 * 60 * 1000,
  OVERGROWTH_PENALTY: 1.5,
  LUCKY_HARVEST_CHANCE: 0.05,
  ACHIEVEMENTS: [
    { key: "harvest_100", name: "Harvest Master", harvests: 100, reward: 1000 },
    { key: "mutation_10", name: "Mutation Maniac", mutations: 10, reward: 500 },
    { key: "expand_1", name: "Land Baron", expansions: 1, reward: 2000 },
  ],
};
